import Head from 'next/head'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import styled from '@emotion/styled'
import { useSession, signIn, signOut } from "next-auth/react";
import { useEffect, useState } from 'react';
import { setCookie } from 'cookies-next';
import Link from 'next/link';
import hadithDb from '../data/islamicQuotes.json';


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session } = useSession();
  const [random, setRandom] = useState(Math.floor(Math.random() * hadithDb.length));


  return (
    <>
      <Head>
        <title>Education App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{padding:"20px"}}>
        <br />
          <h2 style={{textAlign:"center"}}>Education App</h2>
          <br />
          <br />
          <div style={{display:"flex", justifyContent:"center",}}>
            <div style={{padding:"20px", border:"1px solid lightgray", borderRadius:"10px", width:"80%"}}>
              <p style={{textAlign:"center"}}>{hadithDb[random].text}</p>
              <br />
              <Link style={{color:"blue"}} href={hadithDb[random].link}><p style={{textAlign:"center"}}>{hadithDb[random].reference}</p></Link>
            </div>
          </div>
          
          <br />
        {!session ? (
        <div style={{padding:"20px", display:"flex", flexDirection:"column", justifyContent:"center", height:"100%", alignItems:"center"}}>
          <p>Not signed in</p>
          <br />
          <button style={{padding:"10px", border:"1px solid lightgray", borderRadius:"5px"}} onClick={async() => {
            setCookie("role", "teacher");
            signIn()}}>Sign in as Student</button>
            
            <br />
        </div>
        ):
        <div style={{padding:"20px",display:"flex", flexDirection:"column", justifyContent:"center", height:"100%", alignItems:"center"}}>
          
          <h3>{session.user.name}</h3>
          <p style={{opacity:0.7}}>{session.user.email}</p>
          
          <br />
          <Link style={{color:"blue", width:"50%"}} href="/courses">
            <button style={{padding:"10px", border:"1px solid lightgray", borderRadius:"5px", width:"100%"}}>
              Go to courses
            </button>
            </Link>
          <br/>
          
          <button  style={{padding:"10px", border:"1px solid lightgray", borderRadius:"5px", width:"50%"}} onClick={() => signOut()}>Sign out</button>
        </div>}
        </div>
        
      </main>
    </>
  )
}


